version: 2

references:

  container_config: &container_config
    docker:
      - image: rocker/tidyverse:latest

  environment_setup: &environment_setup
    run:
      name: Set environmental variables
      command: |
        Rscript --vanilla \
          -e 'dsc <- read.dcf("DESCRIPTION")' \
          -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
          -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
          >> ${BASH_ENV}

  install_dependencies: &install_dependencies
    run:
      name: Install devtools and dependencies
      command: |
        Rscript \
          -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
          -e 'devtools::install_deps(dependencies = TRUE)'

  package_build: &package_build
    run:
      name: Build package
      command: R CMD build .


jobs:
  check:
    <<: *container_config
    steps:
      - checkout
      - *environment_setup
      - *install_dependencies
      - *package_build
      - run:
        name: Check package
        command: R CMD check "${PKG_TARBALL}" --as-cran --no-manual
      - run:
          name: Check failures
          command: |
            Rscript -e "message(devtools::check_failures(path = '${RCHECK_DIR}'))"
      - run:
          command: mv ${RCHECK_DIR} /tmp/Rcheck
          when: always
      - store_test_results:
          path: /tmp/Rcheck/tests/
          when: always
      - store_artifacts:
          path: /tmp/Rcheck
          when: always

  deploy:
    <<: *container_config
    steps:
      - checkout
      - *environment_setup
      - *install_dependencies
      - *package_build
      - add_ssh_keys:
          fingerprints:
            - "e4:0e:a8:c5:a5:44:d8:ab:1a:53:ee:38:bb:27:42:9b"
      - run: bash ftran_deploy.sh

workflows:
  version: 2
  check_and_deploy:
    jobs:
      - check
      - deploy:
          requires:
            - check
          filters:
            branches:
              only: master

